# IMPORTANT: gitRepo volumes have been deprecated :(
# https://github.com/kubernetes/kubernetes/pull/63445
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# apiVersion: v1
# kind: Pod
# metadata:
#   name: gitrepo-volume-pod
# spec:
#   containers:
#   - image: arm32v7/nginx:alpine
#     name: web-server
#     volumeMounts:
#     - name: html
#       mountPath: /usr/share/nginx/html
#       readOnly: true
#     ports:
#     - containerPort: 80
#       protocol: TCP
#   volumes:
#   - name: html
#     gitRepo:
#       repository: https://github.com/luksa/kubia-website-example.git
#       revision: master
#       directory: .
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# Use this shit instead:

apiVersion: v1
kind: ConfigMap
metadata:
  name: git-clone
data:
  git-clone.sh: |
    #!/bin/sh -e
    REPO=$1
    REF=$2
    DIR=$3
    # Init Containers will re-run on Pod restart. Remove the directory's contents
    # and reprovision when this happens.
    if [ -d "$DIR" ]; then
        rm -rf $( find $DIR -mindepth 1 )
    fi
    git clone $REPO $DIR
    cd $DIR
    git reset --hard $REF
---
apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  initContainers:
  - name: web-server
    image: arm32v7/nginx
    command:
    - /usr/local/git/git-clone.sh
    args:
    - "https://github.com/luksa/kubia-website-example.git"
    - "master"
    - "/repo"
    volumeMounts:
    - name: git-clone
      mountPath: /usr/local/git
    - name: git-repo
      mountPath: /repo
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: git-repo
  volumes:
  - name: git-repo
    emptyDir: {}
  - name: git-clone
    configMap:
      name: git-clone
      defaultMode: 0755
