apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce  # Indicates the number of Nodes (not Pods!) that can use the resource
  storageClassName: ""
